### ISSUE TITLE
Error when running using_predpatt.py 

### ISSUE THREAD

**Issue by IslamAldalabeeh** [hltcoe/PredPatt#8]
I face this error when I try to run doc/using_predpatt.py. any help, please!

Traceback (most recent call last):
  File "C:\Windows\System32\PredPatt\doc\using_predpatt.py", line 8, in <module>
    P = PredPatt.from_sentence(sentence)
  File "c:\windows\system32\predpatt\predpatt\patt.py", line 382, in from_sentence
    parse = _PARSER(sentence)
  File "c:\windows\system32\predpatt\predpatt\util\UDParser.py", line 105, in __call__
    x = self.fresh(*args, **kwargs)
  File "c:\windows\system32\predpatt\predpatt\util\UDParser.py", line 189, in fresh
    raise e
IOError: [Errno 22] Invalid argument

**Comment by sheng-z** [comment]
Hi. I see you're using PredPatt in Windows. We haven't tested PredPatt in Windowns: This error is probably caused by some inner commands that only work in Unix-like systems. 
I suggest you use PredPatt in docker or Unix-like systems.

**Comment by IslamAldalabeeh** [comment]
Thanks a lot for your help.
I use Predpatt in Linux now. but still there are some problems when I am trying run server.
 File "bin/server.py", line 26, in <module>
    parser = Parser.get_instance()
  File "/home/islam/PredPatt/predpatt/util/UDParser.py", line 218, in get_instance
    return Parser(BERKELEY_JAR, GR, CACHE)
  File "/home/islam/PredPatt/predpatt/util/UDParser.py", line 165, in __init__
    self._start_subprocess()
  File "/home/islam/PredPatt/predpatt/util/UDParser.py", line 170, in _start_subprocess
    stdin=PIPE, stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I think the error about accessing the path of code, I try sitting shell=True produces another error.
any suggestion please! 
Thanks in advance.

**Comment by sheng-z** [comment]
PredPatt will use `curl` to download the Berkeley Parser and the Stanford Parser when you call `Parser.get_instance()`.
Can you check if you successfully downloaded them by commanding `ls ~/.PredPatt`?
If they're not there, probably something wrong with your `curl` command.

**Comment by IslamAldalabeeh** [comment]
I check them, the Berkeley Parser and the Stanford Parser successfully downloaded.

**Comment by sheng-z** [comment]
Then it could be the issue of accessing the path as you said, but I'm not able to replicate your error in my Linux system (`Linux 4.4.0-93-generic #116-Ubuntu SMP x86_64 GNU/Linux`). 
A temp workaround for you is to hardcode the paths in line 59-61 of [UDParser.py](https://github.com/hltcoe/PredPatt/blob/master/predpatt/util/UDParser.py#L59).

**Comment by IslamAldalabeeh** [comment]
I was reinstall Predpatt again, but this  error appears.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "predpatt/patt.py", line 382, in from_sentence
    parse = _PARSER(sentence)
  File "predpatt/util/UDParser.py", line 108, in __call__
    x = self.fresh(*args, **kwargs)
  File "predpatt/util/UDParser.py", line 198, in fresh
    return self.to_ud(out)
  File "predpatt/util/UDParser.py", line 108, in __call__
    x = self.fresh(*args, **kwargs)
  File "predpatt/util/UDParser.py", line 130, in fresh
    deps = self.sd.convert_tree(parse)
  File "/usr/local/lib/python2.7/dist-packages/PyStanfordDependencies-0.3.1-py2.7.egg/StanfordDependencies/JPypeBackend.py", line 89, in convert_tree
    raise ValueError("Invalid Penn Treebank tree: %r" % ptb_tree)
ValueError: Invalid Penn Treebank tree: '

any help please.

**Comment by sheng-z** [comment]
Actually the way you're using PredPatt will soon be deprecated. The recommended way is docker+SyntaxNet+PredPatt for which you can find the documentation [here](https://github.com/hltcoe/PredPatt/tree/master/api/rest). It is still under development. We're actively adding more support to it.

**Comment by sheng-z** [comment]
I suppose this issue is solved. Please reopen it if you have more questions.
